{{- if .Values.predefinedKeys.Enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openvpn-predefined-keys
data:
  openvpn-predefined-keys.ca_crt: |
    {{ .Values.predefinedKeys.ca_crt_b64 }}
  openvpn-predefined-keys.server_crt: |
    {{ .Values.predefinedKeys.server_crt_b64 }}
  openvpn-predefined-keys.server_key: |
    {{ .Values.predefinedKeys.server_key_b64 }}
  openvpn-predefined-keys.tlscrypt: |
    {{ .Values.predefinedKeys.tlscrypt_b64 }}
  openvpn-predefined-keys.dh_pem: |
    {{ .Values.predefinedKeys.dh_pem_b64 }}
{{- end }}